---
name: Setup Lint Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
         - name: checkout repo
           uses: actions/checkout@v5

         - name: setup node.js
           uses: actions/setup-node@v5 
           with:
            node-version: '22'  
         
         - name: Install dependencies
           run: npm ci

         - name: Run lint
           run: npm run lint
            
        #  - name: Run tests
        #    run: npm tests
         
